version: 2.1

orbs:
  node-orb: circleci/node@0.0.5

workflows:
  build:
    jobs:
      - lint

jobs:
  lint:
    environment:
      CIRCLE_TEST_REPORTS: &circle_test_report /tmp/test-results
    executor:
      name: node-orb/node
      tag: "10-browsers"
    steps:
      - checkout
      - node-orb/with-cache:
          steps:
            - run:
                command: npm install
      - run:
          name: Add node executables dir to $PATH
          command: echo 'export PATH=node_modules/.bin/:$PATH' >> $BASH_ENV 
      - run:
          name: Lint with report
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/jshint
            npm run lint > $CIRCLE_TEST_REPORTS/jshint/results.xml
      - store_test_results:
          path: *circle_test_report
