version: 2.1

orbs:
  node-orb: circleci/node@0.0.5

workflows:
  build:
    jobs:
      - lint:
          filters:
            branches:
              ignore: master
      - increment_version:
          filters:
            branches:
              only: master

jobs:
  lint:
    environment:
      CIRCLE_TEST_REPORTS: &circle_test_report /tmp/test-results
    executor:
      name: node-orb/node
      tag: "10-browsers"
    steps:
      - checkout
      - node-orb/with-cache:
          steps:
            - run:
                command: npm install
      - run:
          name: Add node executables dir to $PATH
          command: echo 'export PATH=node_modules/.bin/:$PATH' >> $BASH_ENV 
      - run:
          name: Lint with report
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/jshint
            npm run lint > $CIRCLE_TEST_REPORTS/jshint/results.xml
      - store_test_results:
          path: *circle_test_report
  increment_version:
    docker:
      - image: buildpack-deps:stretch-scm
    steps:
      - checkout
      - run:
          name: 'increment version'
          command: |
            hash_diff=$(echo "$CIRCLE_COMPARE_URL" | awk -F"/" '{print $NF}') # e.g) b49753e8fa55...0c0f2efd332a
            if [[ -n "$hash_diff" ]]; then
              for i in $(git diff --name-only $hash_diff *.user.js); do
                ./bin/replace_version.sh $i;
              done
              git add .
              git commit -m "increment version"
              git push
            fi
